### ISSUE TITLE
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authenticate.js'

### ISSUE THREAD

**Issue by daha1989** [randomBrainstormer/MMM-GoogleCalendar#4]
Hi :)
so if I try to execute Step 5 it'll give me the following error:

pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleCalendar $ node authenticate.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authenticate.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

any advise for that?
Thank you in advance.

**Comment by randomBrainstormer** [comment]
Hi! according to the error the module is not found. Try and check if you're in the right directory, try using this command: ls it will list the files in the current directory, if you're in the right place you should see a file called authenticate.js, otherwise you got to navigate to the modules directory and execute `node authenticate.js` inside the `MMM-GoogleCalendar` directory.

**Comment by randomBrainstormer** [comment]
We seem to be facing the same issue [over here](https://github.com/randomBrainstormer/MMM-GoogleCalendar/issues/3#issuecomment-1007016019)

**Comment by georgeismike** [comment]
I am having the same issue.

**Comment by randomBrainstormer** [comment]
summary: there was an error in the documentation, the comamnd should be `node authorize.js` and not `node authenticate.js`. Let me know if you find any more issues.
