### ISSUE TITLE
Error_Auth_Needed

### ISSUE THREAD

**Issue by xIExodusIx** [randomBrainstormer/MMM-GoogleCalendar#74]
Hello,
I have already described this Problem on October 1st. in an other tread here, but nobody reacts within one month. So I try it again with an new Bugreport.

node authorize.js does not  work! The credentials.json File is in the module Folder, but when I run "node authorize.js" I get following Error!: 

node authorize.js
MMM-GoogleCalendar: Error loading credentials [Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'
}
^C
As you can see, I have to press ctrl&C to abort this!

How can I solve this problem? I need my Google-Calendar displayed on the MagicMirror!

Thanks for helping. :-)

**Comment by xIExodusIx** [comment]
Hello, 
Thanks for your Help, in the Modul-Folder is no token.js File. I had understood that this file is created by the authorization process by running "node authorize.js". 
Maybe thats my fault. 
On the other Hand I'm an old german guy and my school english is after all those years pretty bad, so I have some problems following your instructions for setting up the Google-Calendar-API.
I had running MagicMirror since Version 2.16 with MMM-GoogleCalendar and it workt verry fine. After a longtime illnes I tried to setup my MagicMirror again, but now GoogleCalender won't work anymore. I think it is because Goolgle changes something on the access-process to the google-cloud-project. Since MM 2.16 I have the needed google-cloud-project.

So I deleted my old google-cloud-project and tried to create it new. I downloaded the "client_secret....json" File from Google 
and renamed it to credentials.json, I dceleted the MMM-GoogleCalendar folder and installed it new using git clone and npm install. Copied the credentials.json using WinSCP from my PC to  the MMM-GoogleCalendar folder on my Raspberry Pi. Running "node authorize.js" ends in the same Error as before. 
How can I generate the token.json file that is needed for the authorization-process?

**Comment by xIExodusIx** [comment]
I tried something other, I maden an empty token.json file and run "node authorize.js" now I got an other error message and it seems that the credentials.json file is not correct.

The new errors are: 
 MMM-GoogleCalendar: Error loading credentials SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadSavedCredentialsIfExist (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:23:30)
    at async authorize (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:55:16)

The empty token.json file still remains empty.

Maybe this could help to figure out whats wrong here.

**Comment by randomBrainstormer** [comment]
Thank you for your detailed follow-up and for sharing your experience. Let's work together to get this sorted out.

First, I understand the process can be frustrating, especially with changes in API access. The issues you're encountering seem related to where the token.json file should be created.

Here’s what we can try to resolve the issue:

1. **Ensure the Correct Directory**:
Make sure you are in the MMM-GoogleCalendar directory when you run `node authorize.js`. This matters because the script will try to generate the token.json file in the current directory.
2. **Remove Dummy Token**:
Delete any empty token.json file you created previously. Having this empty file might disrupt the process.
3. **Run the Authorization Again**:
Try running `node authorize.js` again. The script should prompt you to open a browser window or provide a link to complete the authorization process with your Google account.
4. **Check for Prompts**:
If you don’t see a browser window or link, there might be output in the terminal regarding where to go for authorization. Make sure any pop-up blockers in your browser are disabled or try running the command on a machine where the browser can open automatically if possible.
5. **Double-Check Credentials**:
Ensure that your `credentials.json` file is set up correctly, downloaded from your Google Cloud project.

Don’t hesitate to let me know how it goes, or if any errors persist, feel free to include them!

**Comment by randomBrainstormer** [comment]
Hi, it sounds like the issue is likely tied to the `credentials.json` file format. Here's how you can ensure it is set up correctly:

1. **Verify `credentials.json` Structure**:
The file should look similar to this:

```json
{
  "installed": {
    "client_id": "xxxxxxxxxxxxxxxxxx-xxxx.apps.googleusercontent.com",
    "project_id": "some-id-from-your-project",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "some-string",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost"
    ]
  }
}
```
Make sure that all keys and values are correctly copied from your Google Developer Console.

2. **Follow the Guide for Correct Setup:**
Double-check the steps in the guide for "[Configure OAuth Consent Screen](https://github.com/randomBrainstormer/MMM-GoogleCalendar?tab=readme-ov-file)". 
You should find the [guide for oauth part in your google cloud project](https://developers.google.com/calendar/api/quickstart/nodejs#configure_the_oauth_consent_screen) , and ensure that your OAuth credentials are correctly set up as a "Desktop application". This is crucial for generating the correct file.  

Your current setup method via SSH and PuTTY should work fine, but you might need to download the credentials.json again and re-upload it to the Raspberry Pi after ensuring it's set as described.

Let me know if this helps or if there are any more issues!

**Comment by xIExodusIx** [comment]
Thank you very much, this solves one fault. :-) My credentials.json file was one long string, after editing I'll get further. Found panother failer in my configuration for the "OAuth Consent Screen configuration". My Usertype is set to "external", can't find a way to switch it to "internal".
I think I will delet the old project and start the whole procedure from scratch.

**Comment by xIExodusIx** [comment]
I'm no Google Workspace User, so I can't switch to "Usertype = Internal" I can only use "Usertype = External". This is, why I don't own a Creditcard for payment, and other payment methodes Google does not show.  
After editing the credentials.json and running "node authorize.js" I now get this error:

MMM-GoogleCalendar: Error loading credentials [Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'
}
Error: The provided keyfile does not define a valid
redirect URI. There must be at least one redirect URI defined, and this sample
assumes it redirects to 'http://localhost:3000/oauth2callback'.  Please edit
your keyfile, and add a 'redirect_uris' section.  For example:

"redirect_uris": [
  "http://localhost:3000/oauth2callback"
]

    at authenticate (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/node_modules/@google-cloud/local-auth/build/src/index.js:55:15)
    at authorize (/home/pi/MagicMirror/modules/MMM-GoogleCalendar/authorize.js:59:18)


But there is a "redirect_uris" section in the credential.js file: --> "redirect_uris": [ 
                                                                                                      "http://localhost"
                                                                                                       ]

**Comment by randomBrainstormer** [comment]
Hi there! 

First off, it’s totally okay for your OAuth user type to be set to External. You don’t need to change this, and there’s no need to worry about payment! I haven’t set up payment for this project either, and using this plugin with Google Cloud doesn’t incur any charges.

The error is saying it can’t find a redirect URI. To fix this, go to the Credentials section in your Google Cloud Console. In the OAuth 2.0 client settings, make sure the redirect_uris include the specific address that your MagicMirror setup needs. For most setups, this will be:
```
http://localhost:3000/
```

If you already have `http://localhost` set a s a authorized redirect URI, just add `http://localhost:3000/` (note the port). You could fill both, "Authorized redirect URIs" and "Authorized JavaScript sources" fields in your credentials page. Once you’ve updated it, download the credentials file again directly from Google Cloud and replace the old file in your MagicMirror setup. 

Also, it’s okay if the new credentials.json file is one long string—it should still work. After making this change, try running node authorize.js again.

Let me know how it goes 🚀

**Comment by xIExodusIx** [comment]
Thank you for helping, 

I added the Port (:3000) for for the "redirect_uris" but now I get the same error like the beginning! 
I run out of clues now. Im turning in circles. :-(

node authorize.js
MMM-GoogleCalendar: Error loading credentials [Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'
}
^C

**Comment by xIExodusIx** [comment]
Hi, I'm using my Windows PC for configure the OAuth consent screen, downloading the "client_secret..."-file to my Windows PC. 
Copying the "client_scret..."-file to my Raspberry I use WinSCP.
On my Raspberry I use "mc (MidnightCommander)", "Nano" etc. all via "Putty"-SSH-connection.
I tried it as you told me, but it is always the same result. And always the same error. It seems that one or more "settings"?! are missing in the "credentials.json" file.
I think I give in, and my new MM will not show my daily tasks and plans anymore. :-( 
That setup to show a simple calender is to high and difficult for me, easy and convenient goes an other way.

Thanks for all your Help

**Comment by xIExodusIx** [comment]
Hi randomBrainstormer,
 I got it, it's working now! :-)
You are right, I had to do the whole authentication process directly from my Raspberry, going through the whole guide with running the "index.js". 
After that running "node authorize.js" went through and created the "token.js".

Now my Google-Calendar is displayd on my MagicMirror.

Again, thanks a lot for helping :-)
